### LOCAL - ping
GET http://localhost:8080/ping

### LOCAL - products
GET http://localhost:8080/products

### LOCAL - product
GET http://localhost:8080/product/AAA25

### LOCAL - best_seller_product
GET http://localhost:8080/best_seller_product

### LOCAL - relevant_product
GET http://localhost:8080/relevant_product