version: "3.2"
services:
  api:
    container_name: kiren-api
    image: kiren-api
    build:
      context: ../../
      dockerfile: deployment/prd/Dockerfile
    networks:
      - kiren
    ports:
      - ${KIREN_API_PORT:-8080}:8080
    environment:
      APP_PORT: 8080
      APP_ENV: local
  mysql:
    container_name: kiren-mysql
    image: mysql
    restart: always
    networks:
      - kiren
    ports:
      - ${KIREN_MYSQL_PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: password

networks:
  kiren:
    external: false
