version: "3.2"
services:
  api:
    container_name: kiren-api
    image: kiren-api
    build:
      context: ../../
      dockerfile: deployment/prd/Dockerfile
    networks:
      - kiren
    ports:
      - ${KIREN_LOCALHOST_PORT:-8080}:8080
    environment:
      APP_PORT: 8080
      APP_ENV: local

networks:
  kiren:
    external: false
